#!/usr/bin/env python3
"""Generate one Airflow DAG file per node from terraform output.

Usage:
  1. Fill in generate_dags.env with venue-specific constants.
  2. Run: python generate_dags.py
"""

import json
import subprocess
import sys
from pathlib import Path

ENV_FILE = Path(__file__).parent / "generate_dags.env"
TERRAFORM_DIR = Path(__file__).parent


def load_env_file(path: Path) -> dict:
    env = {}
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            key, _, value = line.partition("=")
            env[key.strip()] = value.strip()
    return env


def get_terraform_output() -> dict:
    result = subprocess.run(
        ["terraform", "output", "-json", "task_definition_arns"],
        cwd=TERRAFORM_DIR,
        capture_output=True,
        text=True,
        check=True,
    )
    return json.loads(result.stdout)


def generate_dag(node_name: str, task_arn: str, env: dict) -> str:
    node_upper = node_name.upper()
    node_lower = node_name.lower()
    venue = env["VENUE"].lower()
    cluster = env["ECS_CLUSTER_NAME"]
    subnets = json.loads(env["ECS_SUBNETS"])
    security_groups = json.loads(env["ECS_SECURITY_GROUPS"])

    return f'''"""PDS {node_upper} Registry Sweeper DAG.

This DAG runs the PDS {node_upper} Registry Sweeper on a scheduled basis.
It executes an ECS task on Fargate to perform registry sweeping operations.

This DAG is compatible with Airflow 3.0+
Auto-generated by generate_dags.py — do not edit manually.
"""

from datetime import datetime, timedelta
from airflow import DAG
from airflow.operators.bash import BashOperator
from airflow.providers.amazon.aws.operators.ecs import EcsRunTaskOperator
from airflow.utils.trigger_rule import TriggerRule

NODE_NAME = "{node_upper}"
DAG_ID = "PDS_{node_upper}-registry-sweeper"
ECS_TASK_DEFINITION_ARN = "{task_arn}"
ECS_CLUSTER_NAME = "{cluster}"
ECS_LAUNCH_TYPE = "FARGATE"
ECS_SUBNETS = {json.dumps(subnets)}
ECS_SECURITY_GROUPS = {json.dumps(security_groups)}

default_args = {{
    "owner": "airflow",
    "depends_on_past": False,
    "retries": 0,
    "retry_delay": timedelta(minutes=5),
}}

dag = DAG(
    dag_id=DAG_ID,
    description="Registry sweeper for PDS {node_upper}",
    schedule=timedelta(hours=1),
    start_date=datetime(2023, 1, 13),
    catchup=False,
    max_active_runs=1,
    default_args=default_args,
    tags=["pds", "registry", "sweeper", "ecs"],
)

print_start_time = BashOperator(
    task_id="Print_Start_Time",
    dag=dag,
    bash_command='echo "Registry {node_upper} Sweeper workflow started at $(date)"',
)

registry_sweeper = EcsRunTaskOperator(
    task_id="Run_Registry_Sweeper",
    dag=dag,
    cluster=ECS_CLUSTER_NAME,
    task_definition=ECS_TASK_DEFINITION_ARN,
    launch_type=ECS_LAUNCH_TYPE,
    network_configuration={{
        "awsvpcConfiguration": {{
            "securityGroups": ECS_SECURITY_GROUPS,
            "subnets": ECS_SUBNETS,
            "assignPublicIp": "DISABLED",
        }},
    }},
    overrides={{}},
    awslogs_group="/ecs/pds-{node_lower}-{venue}-registry-sweepers-task",
    awslogs_stream_prefix="ecs/pds-{node_lower}-{venue}-registry-sweepers-container",
)

print_end_time = BashOperator(
    task_id="Print_End_Time",
    dag=dag,
    bash_command='echo "Registry {node_upper} Sweeper workflow completed at $(date)"',
    trigger_rule=TriggerRule.ALL_SUCCESS,
)

print_start_time >> registry_sweeper >> print_end_time
'''


def main():
    if not ENV_FILE.exists():
        print(f"Error: {ENV_FILE} not found. Copy generate_dags.env.example and fill in your values.", file=sys.stderr)
        sys.exit(1)

    env = load_env_file(ENV_FILE)

    required = {"ECS_CLUSTER_NAME", "ECS_SUBNETS", "ECS_SECURITY_GROUPS", "VENUE"}
    missing = required - env.keys()
    if missing:
        print(f"Error: missing keys in {ENV_FILE}: {', '.join(sorted(missing))}", file=sys.stderr)
        sys.exit(1)

    try:
        task_arns = get_terraform_output()
    except subprocess.CalledProcessError as e:
        print(f"Error running terraform output: {e.stderr}", file=sys.stderr)
        sys.exit(1)

    output_dir = Path(env.get("DAGS_OUTPUT_DIR", "."))
    output_dir.mkdir(parents=True, exist_ok=True)

    for node_name, task_arn in task_arns.items():
        content = generate_dag(node_name, task_arn, env)
        out_path = output_dir / f"PDS_{node_name.upper()}-sweeper.py"
        out_path.write_text(content)
        print(f"Generated {out_path}")


if __name__ == "__main__":
    main()
